FROM maven_spring-boot-mongodb-login-package AS spring-boot-mongodb-login-package
WORKDIR /app
COPY . .
RUN mvn clean package

FROM eclipse-temurin AS spring-boot-mongodb-login-deploy
COPY --from=spring-boot-mongodb-login-package app/target/*.jar application.jar
ENTRYPOINT ["java","-jar","/application.jar"]
EXPOSE 8080